# Generated by Django 4.0.4 on 2023-07-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='location',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='addproduct',
            old_name='product',
            new_name='pname',
        ),
    ]
