# Generated by Django 4.0.4 on 2023-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_rename_location_addproduct_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addmove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpname', models.CharField(max_length=50)),
                ('orgin', models.CharField(max_length=50)),
                ('destiny', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
